name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: MichaelKennedy_Resume.tex
        
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
          id: download
              with:
                    name: 'my-artifact'
                          path: ./

      - name: 'Echo download path'
          run: echo ${{steps.download.outputs.download-path}}
