name: Compile LaTeX File and Deploy to Github Pages

on:
  create:
    tags:
      - 'w[0-9]+p[0-9]-v[0-9]+\.[0-9]+\.[0-9]'

jobs:
  compile_latex:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v3
    - name: Set Resume Name Environment Variable
      run: echo "RESUME_NAME=$(ls | grep *Resume.tex | cut -d. -f1)" >> $GITHUB_ENV
    - name: Generate Changelog
      run: echo "# Changelog " > ${{ github.workspace }}-CHANGELOG.md
    - name: Convert to PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: ${{ env.RESUME_NAME }}.tex
        post_compile: "latexmk -c"
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        draft: true
        tag: ${GITHUB_REF/refs\/tags\//}
        artifacts: ${{ env.RESUME_NAME }}.pdf
        bodyFile: ${{ github.workspace }}-CHANGELOG.md
        token: ${{ secrets.RESUME_RELEASE }}
