name: Compile LaTeX File and Deploy to Github Pages

on:
  push:
    branches:
      - main


jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v3
    - name: Convert to PDF
      id: convert-to-pdf
      uses: xu-cheng/latex-action@v2
      with:
        root_file: MichaelKennedy_Resume.tex
    - name: Print Result
      run: ls -l



