name: Compile LaTeX File and Deploy to Github Pages

on:
  push:
    branches:
      - main


jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v3
    - name: Set Resume Name
      run: echo "RESUME_NAME=$(ls | grep *Resume.tex | cut -d. -f1)" >> $GITHUB_ENV
    - name: Convert to PDF
      id: convert-to-pdf
      uses: xu-cheng/latex-action@v2
      with:
        root_file: ${{ env.RESUME_NAME }}.tex
        post_compile: "latexmk -c"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Resume
        path: ${{ env.RESUME_NAME }}.pdf


  publish_to_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: Resume
      - name: Check Artifact
        run: ls -l




