name: Compile LaTeX File

on:
  push

jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v3
    - uses: fregante/setup-git-user@v1
    - name: Set Resume Name Environment Variable
      run: echo "RESUME_NAME=$(ls | grep *Resume.tex | cut -d. -f1)" >> $GITHUB_ENV
    - name: Convert to PDF
      uses: xu-cheng/latex-action@v2
      with:
        root_file: ${{ env.RESUME_NAME }}.tex
        post_compile: "latexmk -c"
    - name: Push to Repo
      run: |
          git add ${{ env.RESUME_NAME }}.pdf
          git commit -m "Automated push"
          git push --force

  build_pages_site:
    needs: [compile_latex]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Files
        uses: actions/checkout@v3
      - name: Build Pages
        uses: actions/jekyll-build-pages@v1
      - name: Deploy Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.RESUME_RELEASE }}
