name: Compile LaTeX Resume and Push To Pages Branches

on:
  push:
    branches: ['staging1', 'staging2']
    paths: ['*.tex']
  workflow_dispatch:

jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v4
    - name: Compile TeX File
      uses: xu-cheng/latex-action@v3
      with:
        root_file: "*.tex"
        post_compile: "latexmk -c"
    - name: Push to pages branch
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name actions-user
          git add --force *
          git commit -m "$(git log -1 --pretty='%s')"
          if [ $GITHUB_REF == "refs/heads/staging1"]; then
            git push $(git ls-remote --get-url origin) staging1:prod --force
          else
            git push $(git ls-remote --get-url origin) staging2:ats-friendly --force
          fi



          
