name: Compile LaTeX Resume and Push To GH Pages

on:
  push:
    branches: ['main']
    paths: ['*.tex']
  workflow_dispatch:

jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v3
    - name: Set Compile Flag
      run: |
        latex_files=$(find . -type f -name "*.tex")
        first_tex_file=$(echo "$latex_files" | head -n 1)
        echo "FIRST_TEX_FILE=$first_tex_file" >> $GITHUB_ENV

        echo "$GITHUB_REF"
        if [ $GITHUB_REF == 'refs/heads/main' ]; then
          echo ARGS="-interaction=nonstopmode -jobname=with_icon \"\def\disableiconfalse\input{$first_tex_file}\"" >> $GITHUB_ENV
        else
          echo ARGS="-interaction=nonstopmode -jobname=without_icon \"\def\disableicontrue\input{$first_tex_file}\"" >> $GITHUB_ENV
        fi

        echo "Arguments: $ARGS"
    # - name: Compile TeX File
    #   uses: xu-cheng/latex-action@v3
    #   with:
    #     root_file: { $FIRST_TEX_FILE }
    #     glob_root_file: true
    #     post_compile: "latexmk -c"
    # - name: Push to pages branch
    #   run: |
    #       git config --local user.email "actions@github.com"
    #       git config --local user.name actions-user
    #       git add --force *
    #       git commit -m "$(git log -1 --pretty='%s')"
    #       git push $(git ls-remote --get-url origin) main:gh-pages --force
