name: Compile LaTeX Resume and Push To GH Pages

on:
  push:
    branches: ['main']
    paths: ['*.tex']
  workflow_dispatch:

jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v3
    - name: Set Environment Variables
      run: |
        echo "RESUME_NAME=$(ls | grep *Resume.tex | cut -d. -f1)" >> $GITHUB_ENV
        exists=false
        if [[ $(git branch -a | grep "remotes/origin/gh-pages") ]]; then
          exists=true
        fi
        echo "PAGES_BRANCH_EXISTS=$exists" >> $GITHUB_ENV
        echo "${{ env.PAGES_BRANCH_EXISTS }}"
    - name: Compile TeX File
      uses: xu-cheng/latex-action@v2
      with:
        root_file: ${{ env.RESUME_NAME }}.tex
        post_compile: "latexmk -c"
    - name: Push to pages branch
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name actions-user
          git add --force *
          git commit -m "$(git log -1 --pretty='%s')"
          git push $(git ls-remote --get-url origin) main:gh-pages --force
