name: Deploy Resume to Github Pages

on:
  workflow_dispatch:


jobs:
  get_pdf_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get API Data
        run: |
          echo "API_DATA=$(curl https://api.github.com/repos/${{ github.repository }}/releases/latest )" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Print Environment Variables
        run: echo "${{ env.API_DATA }}"

