name: Deploy Resume to Github Pages

on:
  workflow_dispatch:


jobs:
  get_pdf_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get API Data
        run: |
          echo "BRANCH_ORIGIN=$(curl https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name' | awk -F\- '{print $1}')" >> $GITHUB_ENV
          echo "DOWNLOAD_URL=$(curl https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.assets[0].browser_download_url')" >> $GITHUB_ENV
          echo "API_DATA='$(curl https://api.github.com/repos/${{ github.repository}}/releases/latest)'" >> $GITHUB_ENV
      - name: Print Environment Variables
        run: echo "${{ env.API_DATA }}"

