name: Deploy Resume to Github Pages

on:
  push:
    branches:
      - main

jobs:
  get_pdf_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set Download URL
        run: echo "DOWNLOAD_URL=$(curl https://api.github.com/repos/${{ github.repository }}/releases/latest | jq '.assets[0].browser_download_url')" >> $GITHUB_ENV
      - name: Download PDF From Release
        run: curl -L -O ${{ env.DOWNLOAD_URL }}

