name: Deploy Resume to Github Pages

on:
  push:
    branches:
      - main

jobs:
  get_pdf_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install cURL
        run: sudo apt-get install -y curl
      - name: Set Download URL
        run: echo "DOWNLOAD_URL=$(curl https://api.github.com/repos/${{ github.repository }}/releases/latest | jq '.assets[0].browser_download_url')" >> $GITHUB_ENV
      - name: Check env var
        run: echo ${{ env.DOWNLOAD_URL }}
