name: Deploy Resume to Github Pages

on:
  workflow_dispatch:


jobs:
  get_pdf_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get API Data
        run: echo "API_DATA=$(curl https://api.github.com/repos/${{ github.repository }}/releases/latest)" >> $GITHUB_ENV
      - name: Set Download URL
        run: |
          echo "DOWNLOAD_URL=$( ${{ env.API_DATA }} | jq '.assets[0].browser_download_url')" >> $GITHUB_ENV
          echo "BRANCH_ORIGIN=$( ${{ env.API_DATA }} | jq '.tag_name)" >> $GITHUB_ENV
        
      - name: Print Environment Variables
        run: |
          echo ${{ env.DOWNLOAD_URL }} \
          echo ${{ env.BRANCH_ORIGIN }} \


