name: Deploy Resume to Github Pages

on:
  workflow_dispatch:


jobs:
  get_pdf_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Download URL
        run: echo "DOWNLOAD_URL=$(curl https://api.github.com/repos/${{ github.repository }}/releases/latest | jq '.assets[0].browser_download_url')" >> $GITHUB_ENV
      - name: Download PDF From Release
        run: curl -L -O ${{ env.DOWNLOAD_URL }}
      - name: Commit and Push Changes
        run: |
          git remote set-url --push origin https://${GITHUB_REPOSITORY%/*}:${{ secrets.RESUME_RELEASE }}@github.com/${{ github.repository }}
          git status
        


