name: Initialize tex files

on:
  push:
    branches: ['main']
    paths: ['*.tex']
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v4
    - name: Config git credentials
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name actions-user

    - name: Push to staging 1 branch
      run: |
          git switch staging1
          git checkout origin/main -- *.tex
          git add --force *
          git commit -m "$(git log -1 --pretty='%s')"
          git push --force

    - name: Push to staging 2 branch
      run: | 
          git switch staging2
          git checkout origin/main -- *.tex

          latex_files=$(find . -type f -name "*.tex")
          first_tex_file=$(echo "$latex_files" | head -n 1)

          sed -i 's/\\disablesymbolfalse/\\disablesymboltrue/g' $first_tex_file
          git add --force *
          git commit -m "$(git log -1 --pretty='%s')"
          git push --force