name: Initialize tex files

on:
  push:
    branches: ['main']
    paths: ['*.tex']
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Files
      uses: actions/checkout@v4
    - name: Set Tex File Name
      run: |
        latex_files=$(find . -type f -name "*.tex")
        first_tex_file=$(echo "$latex_files" | head -n 1)
        echo "TEX_FILE=$first_tex_file" >> $GITHUB_ENV
    - name: Config git credentials
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name actions-user
    - name: Push to staging 1 branch
      run: |
          git add --force *
          git commit -m "$(git log -1 --pretty='%s')"
          git push $(git ls-remote --get-url origin) main:staging1 --force

    - name: Push to staging 2 branch
      run: | 
          sed -i 's/\\disablesymbolfalse/\\disablesymboltrue/g' $first_tex_file
          git add --force *
          git commit -m "$(git log -1 --pretty='%s')"
          git push $(git ls-remote --get-url origin) main:staging2 --force