name: Test File


on:
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v3
      - name: Print Last Commit Message
        run: echo "$(git reflog -1 | sed 's/^.*: //')"
